name: autorun
on:
  push:
    branches:
      - master
  schedule:
    - cron: '0 15 * * *'

jobs:
  autorun:
    runs-on: ubuntu-20.04
    steps:
      - name: checkout
        uses: actions/checkout@v2
      - name: install requirements
        run: pip3 install requests
      - name: run code
        run: python3 run.py -u ${{ secrets.USERNAME }} -p ${{ secrets.PASSWORD }}
